support OCS extension
Squashed OCS commits on top of sonic-net master.

Co-authored-by: Cursor <cursoragent@cursor.com>

diff --git a/scripts/reboot b/scripts/reboot
--- a/scripts/reboot
+++ b/scripts/reboot
@@ -2,11 +2,8 @@
 
 declare -r EXIT_SUCCESS=0
 declare -r EXIT_ERROR=1
-declare -r EXIT_TIMEOUT=2
 declare -r WATCHDOG_UTIL="/usr/local/bin/watchdogutil"
 declare -r PRE_REBOOT_HOOK="pre_reboot_hook"
-
-source reboot_smartswitch_helper
 
 DEVPATH="/usr/share/sonic/device"
 PLAT_REBOOT="platform_reboot"
@@ -14,17 +11,12 @@ PLATFORM_UPDATE_REBOOT_CAUSE="platform_update_reboot_cause"
 REBOOT_CAUSE_FILE="/host/reboot-cause/reboot-cause.txt"
 PLATFORM_REBOOT_PRE_CHECK="platform_reboot_pre_check"
 REBOOT_TIME=$(date)
-REBOOT_CONFIG_FILE="/etc/sonic/reboot.conf"
 
 # Reboot immediately if we run the kdump capture kernel
 VMCORE_FILE=/proc/vmcore
 if [ -e $VMCORE_FILE -a -s $VMCORE_FILE ]; then
         echo "We have a /proc/vmcore, then we just kdump'ed"
         echo "Kernel Panic [Time: ${REBOOT_TIME}]" > ${REBOOT_CAUSE_FILE}
-        makedumpfile --dump-dmesg /proc/vmcore /tmp/dmesg
-        if  grep -q "Kernel panic - not syncing: Out of memory" /tmp/dmesg; then
-            echo "Kernel Panic - Out of memory [Time: ${REBOOT_TIME}]" > ${REBOOT_CAUSE_FILE}
-        fi
         sync
         PLATFORM=$(grep -oP 'sonic_platform=\K\S+' /proc/cmdline)
         if [ ! -z "${PLATFORM}" -a -x ${DEVPATH}/${PLATFORM}/${PLAT_REBOOT} ]; then
@@ -45,19 +37,10 @@ EXIT_NEXT_IMAGE_NOT_EXISTS=4
 EXIT_SONIC_INSTALLER_VERIFY_REBOOT=21
 EXIT_PLATFORM_FW_AU_FAILURE=22
 PLATFORM_FWUTIL_AU_REBOOT_HANDLE="platform_fw_au_reboot_handle"
-PLATFORM_JSON_FILE="platform.json"
-PLATFORM_JSON_PATH="${DEVPATH}/${PLATFORM}/${PLATFORM_JSON_FILE}"
 REBOOT_SCRIPT_NAME=$(basename $0)
 REBOOT_TYPE="${REBOOT_SCRIPT_NAME}"
 TAG_LATEST=no
 REBOOT_FLAGS=""
-SMART_SWITCH="no"
-DPU_MODULE_NAME=""
-REBOOT_DPU="no"
-PRE_SHUTDOWN="no"
-BLOCKING_MODE="no"
-BLOCKING_MODE_TIMEOUT_IN_SECOND=180
-SHOW_TIMER="no"
 
 function debug()
 {
@@ -81,12 +64,9 @@ function stop_pmon_service()
 {
      CONTAINER_STOP_RC=0
      debug "Stopping pmon docker"
-     if [[ "${PRE_SHUTDOWN}" == "yes" ]]; then
-         systemctl disable pmon
-     fi
      systemctl stop pmon || debug "Ignore stopping pmon error $?"
      docker kill pmon &> /dev/null || CONTAINER_STOP_RC=$?
-     if [[ $CONTAINER_STOP_RC -ne 0 ]]; then
+     if [[ CONTAINER_STOP_RC -ne 0 ]]; then
         debug "Failed killing container pmon RC $CONTAINER_STOP_RC ."
      fi
 }
@@ -98,7 +78,7 @@ function stop_sonic_services()
         systemctl stop mux
     fi
 
-    if [[ x"$ASIC_TYPE" != x"mellanox" && x"$ASIC_TYPE" != x"pensando" ]]; then
+    if [[ x"$ASIC_TYPE" != x"mellanox" ]]; then
         ASIC_CONF=${DEVPATH}/$PLATFORM/asic.conf
         if [ -f "$ASIC_CONF" ]; then
             source $ASIC_CONF
@@ -122,9 +102,7 @@ function stop_sonic_services()
 function stop_services_asan()
 {
     debug "Stopping swss for ASAN"
-    if [[ x"$ASIC_TYPE" != x"pensando" ]]; then
-        systemctl stop swss
-    fi
+    systemctl stop swss
 }
 
 function clear_warm_boot()
@@ -137,7 +115,7 @@ function clear_warm_boot()
     if [[ -f ${WARM_DIR}/${REDIS_FILE} ]]; then
         mv -f ${WARM_DIR}/${REDIS_FILE} ${WARM_DIR}/${REDIS_FILE}.${TIMESTAMP} || /bin/true
     fi
-    /sbin/kexec -u -a || /bin/true
+    /sbin/kexec -u || /bin/true
 }
 
 SCRIPT=$0
@@ -150,10 +128,6 @@ function show_help_and_exit()
     echo " "
     echo "    Available options:"
     echo "        -h, -? : getting this help"
-    echo "        -d : DPU module name on a smart switch, option is invalid when on DPU"
-    echo "        -p : Pre-shutdown steps on DPU, invalid on NPU"
-    echo "        -b : Enable the command to run in blocking mode"
-    echo "        -v : Print out detail logs. For blocking mode will print dots to identify the script is running"
 
     exit ${EXIT_SUCCESS}
 }
@@ -180,7 +154,7 @@ function reboot_pre_check()
         ${DEVPATH}/${PLATFORM}/${PLATFORM_REBOOT_PRE_CHECK}
         [[ $? -ne 0 ]] && exit $?
     fi
-
+    
     # Verify the next image by sonic-installer
     local message=$(sonic-installer verify-next-image 2>&1)
     if [ $? -ne 0 ]; then
@@ -204,30 +178,19 @@ function check_conflict_boot_in_fw_update()
 
 function parse_options()
 {
-    while getopts "h?vfpd:b" opt; do
+    while getopts "h?vf" opt; do
         case ${opt} in
             h|\? )
                 show_help_and_exit
                 ;;
             v )
                 VERBOSE=yes
-                SHOW_TIMER="yes"
                 ;;
             t )
                 TAG_LATEST=no
                 ;;
             f )
                 REBOOT_FLAGS+=" -f"
-                ;;
-            d )
-                REBOOT_DPU="yes"
-                DPU_MODULE_NAME="$OPTARG"
-                ;;
-            p )
-                PRE_SHUTDOWN="yes"
-                ;;
-            b )
-                BLOCKING_MODE="yes"
                 ;;
         esac
     done
@@ -252,32 +215,62 @@ function linecard_reboot_notify_supervisor()
     fi
 }
 
-function parse_config_file
+function is_molex_platform()
 {
-    if [ -f "$REBOOT_CONFIG_FILE" ]; then
-        while IFS='=' read -r key value; do
-            key=$(echo "$key" | xargs)
-            value=$(echo "$value" | xargs)
-            case $key in
-                blocking_mode)
-                    [ "${value}" = "true" ] && BLOCKING_MODE="yes"
-                    ;;
-                blocking_mode_timeout)
-                    [[ "${value}" =~ ^[0-9]+$ ]] && BLOCKING_MODE_TIMEOUT_IN_SECOND=$(value)
-                    ;;
-                show_timer)
-                    [ "${value}" = "true" ] && SHOW_TIMER="yes"
-                    ;;
-                *)
-                    debug "WARNING: Unknown config ${key}=${value} found in config file ${REBOOT_CONFIG_FILE}" 
-                    ;;
-            esac
-        done < "$REBOOT_CONFIG_FILE"
+    [[ "${PLATFORM}" == *molex* ]]
+}
+
+function handle_platform_reboot_actions()
+{
+    local PLATFORM_FW_AU_RC=0
+
+    if [[ -x ${DEVPATH}/${PLATFORM}/${PLATFORM_FWUTIL_AU_REBOOT_HANDLE} ]]; then
+        debug "Handling task file for boot type ${REBOOT_TYPE}"
+        ${DEVPATH}/${PLATFORM}/${PLATFORM_FWUTIL_AU_REBOOT_HANDLE} ${REBOOT_TYPE} || PLATFORM_FW_AU_RC=$?
+        if [[ $PLATFORM_FW_AU_RC -ne 0 ]]; then
+            debug "ERROR: Failed to handle the platform firmware auto-update for ${REBOOT_TYPE} Exit code: $PLATFORM_FW_AU_RC"
+            exit "${EXIT_PLATFORM_FW_AU_FAILURE}"
+        fi
+    fi
+
+    if [ -x ${DEVPATH}/${PLATFORM}/${PLATFORM_UPDATE_REBOOT_CAUSE} ]; then
+        debug "updating reboot cause for ${PLATFORM}"
+        ${DEVPATH}/${PLATFORM}/${PLATFORM_UPDATE_REBOOT_CAUSE}
+    fi
+
+    if [ -x ${DEVPATH}/${PLATFORM}/${PRE_REBOOT_HOOK} ]; then
+        debug "Executing the pre-reboot script"
+        ${DEVPATH}/${PLATFORM}/${PRE_REBOOT_HOOK}
+        EXIT_CODE="$?"
+        if [[ "${EXIT_CODE}" != "${EXIT_SUCCESS}" ]]; then
+            debug "WARNING: Failed to handle pre-reboot script: rc=${EXIT_CODE}"
+        fi
+    fi
+
+    if [ -x ${WATCHDOG_UTIL} ]; then
+        debug "Enabling the Watchdog before reboot"
+        ${WATCHDOG_UTIL} arm
+    fi
+
+    if [ -x ${DEVPATH}/${PLATFORM}/${PLAT_REBOOT} ]; then
+        VERBOSE=yes debug "Rebooting with platform ${PLATFORM} specific tool ..."
+        ${DEVPATH}/${PLATFORM}/${PLAT_REBOOT} $@
+
+        # There are a couple reasons execution reaches here:
+        #
+        # 1. The vendor platform reboot returned after scheduled the platform specific reboot.
+        #    This is a vendor platform reboot code bug but it happens.
+        # 2. The vendor platform reboot failed. e.g. due to platform driver didn't load properly.
+        #
+        # As result if the reboot script reaches here. We should make the reboot happen.
+        # Sleep 1 second before calling /sbin/reboot to accommodate situation #1 above.
+        sleep 1
+
+        VERBOSE=yes debug "Platform specific reboot failed!" >&2
     fi
 }
 
 parse_options $@
-parse_config_file
 
 # Exit if not superuser
 if [[ "$EUID" -ne 0 ]]; then
@@ -286,18 +279,6 @@ if [[ "$EUID" -ne 0 ]]; then
 fi
 
 debug "User requested rebooting device ..."
-
-handle_smart_switch "$REBOOT_DPU" "$PRE_SHUTDOWN" "$DPU_MODULE_NAME"
-smart_switch_result=$?
-if [[ $smart_switch_result -ne 0 ]]; then
-    exit $smart_switch_result
-fi
-
-# On a smartswitch, complete the DPU reboot and exit
-smartswitch=$(is_smartswitch)
-if [ "$smartswitch" == "True" ] && [ "$REBOOT_DPU" == "yes" ]; then
-    exit $smart_switch_result
-fi
 
 check_conflict_boot_in_fw_update
 
@@ -309,6 +290,12 @@ tag_images
 
 # Linecard reboot notify supervisor
 linecard_reboot_notify_supervisor
+
+# For Molex platforms, run platform reboot hooks before stopping SONiC services
+# because some firmware auto-update/reset steps require HAL services in syncd to remain available.
+if is_molex_platform; then
+    handle_platform_reboot_actions "$@"
+fi
 
 # Stop SONiC services gracefully.
 stop_sonic_services
@@ -328,88 +315,15 @@ sync
 /sbin/fstrim -av
 sleep 3
 
-if [[ -x ${DEVPATH}/${PLATFORM}/${PLATFORM_FWUTIL_AU_REBOOT_HANDLE} ]]; then
-    debug "Handling task file for boot type ${REBOOT_TYPE}"
-    ${DEVPATH}/${PLATFORM}/${PLATFORM_FWUTIL_AU_REBOOT_HANDLE} ${REBOOT_TYPE} || PLATFORM_FW_AU_RC=$?
-    if [[ $PLATFORM_FW_AU_RC -ne 0 ]]; then
-        debug "ERROR: Failed to handle the platform firmware auto-update for ${REBOOT_TYPE} Exit code: $PLATFORM_FW_AU_RC"
-        exit "${EXIT_PLATFORM_FW_AU_FAILURE}"
-    fi
+# sync the current system time to CMOS
+systemctl stop hwclock.service hwclock.timer
+if [ -x /sbin/hwclock ]; then
+    /sbin/hwclock -w || /bin/true
 fi
 
-if [ -x ${DEVPATH}/${PLATFORM}/${PLATFORM_UPDATE_REBOOT_CAUSE} ]; then
-    debug "updating reboot cause for ${PLATFORM}"
-    ${DEVPATH}/${PLATFORM}/${PLATFORM_UPDATE_REBOOT_CAUSE}
-fi
-
-if [ -x ${DEVPATH}/${PLATFORM}/${PRE_REBOOT_HOOK} ]; then
-    debug "Executing the pre-reboot script"
-    ${DEVPATH}/${PLATFORM}/${PRE_REBOOT_HOOK}
-    EXIT_CODE="$?"
-    if [[ "${EXIT_CODE}" != "${EXIT_SUCCESS}" ]]; then
-        debug "WARNING: Failed to handle pre-reboot script: rc=${EXIT_CODE}"
-    fi
-fi
-
-if [ -x ${WATCHDOG_UTIL} ]; then
-    debug "Enabling the Watchdog before reboot"
-    ${WATCHDOG_UTIL} arm
-fi
-
-if [[ "${PRE_SHUTDOWN}" == "yes" ]]; then
-    debug "${DPU_MODULE_NAME} pre-shutdown steps are completed"
-    exit ${EXIT_SUCCESS}
-fi
-
-if [ -x ${DEVPATH}/${PLATFORM}/${PLAT_REBOOT} ]; then
-    VERBOSE=yes debug "Rebooting with platform ${PLATFORM} specific tool ..."
-    ${DEVPATH}/${PLATFORM}/${PLAT_REBOOT} $@
-
-    # There are a couple reasons execution reaches here:
-    #
-    # 1. The vendor platform reboot returned after scheduled the platform specific reboot.
-    #    This is a vendor platform reboot code bug but it happens.
-    # 2. The vendor platform reboot failed. e.g. due to platform driver didn't load properly.
-    #
-    # As result if the reboot script reaches here. We should make the reboot happen.
-    # Sleep 1 second before calling /sbin/reboot to accommodate situation #1 above.
-    sleep 1
-
-    VERBOSE=yes debug "Platform specific reboot failed!" >&2
+if ! is_molex_platform; then
+    handle_platform_reboot_actions "$@"
 fi
 
 VERBOSE=yes debug "Issuing OS-level reboot ..." >&2
-
-if [[ "${BLOCKING_MODE}" != "yes" ]]; then
-    # In non blocking mode, we will remain the original logic.
-    exec /sbin/reboot ${REBOOT_FLAGS}
-else
-
-    REBOOT_START_TIME=$(date +%s)
-    /sbin/reboot ${REBOOT_FLAGS}
-    if [[ "${BLOCKING_MODE}" == "yes" ]]; then
-        # In blocking mode, we just deadloop here to avoid more output generated.
-        BLOCKING_TIMER=1
-        sleep 1
-        while true; do
-            if [ "${SHOW_TIMER}" == "yes" ]; then
-                if [ "${BLOCKING_TIMER}" -ge 50 ]; then
-                    BLOCKING_TIMER=1
-                    echo "."
-                else
-                    let BLOCKING_TIMER++
-                    echo -n "."
-                fi
-            fi
-
-            CURRENT_TIME=$(date +%s)
-            ELAPSED=$((CURRENT_TIME - REBOOT_START_TIME))
-            if (( ELAPSED >= BLOCKING_MODE_TIMEOUT_IN_SECOND )); then
-                echo "[REBOOT FAILED] The reboot used $(ELAPSED)seconds while the timeout is configured as $(BLOCKING_MODE_TIMEOUT_IN_SECOND)seconds"
-                exit ${EXIT_TIMEOUT}
-            fi
-
-            sleep 10
-        done
-    fi
-fi
+exec /sbin/reboot ${REBOOT_FLAGS}
